// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// run_simulation_cpp
List run_simulation_cpp(NumericVector close_prices, NumericVector high_prices, NumericVector low_prices, IntegerVector signals, double initial_cash, double stop_loss_pct);
RcppExport SEXP _quantlab_run_simulation_cpp(SEXP close_pricesSEXP, SEXP high_pricesSEXP, SEXP low_pricesSEXP, SEXP signalsSEXP, SEXP initial_cashSEXP, SEXP stop_loss_pctSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type close_prices(close_pricesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type high_prices(high_pricesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type low_prices(low_pricesSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type signals(signalsSEXP);
    Rcpp::traits::input_parameter< double >::type initial_cash(initial_cashSEXP);
    Rcpp::traits::input_parameter< double >::type stop_loss_pct(stop_loss_pctSEXP);
    rcpp_result_gen = Rcpp::wrap(run_simulation_cpp(close_prices, high_prices, low_prices, signals, initial_cash, stop_loss_pct));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_quantlab_run_simulation_cpp", (DL_FUNC) &_quantlab_run_simulation_cpp, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_quantlab(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
