# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Run Path-Dependent Portfolio Simulation (C++)
#'
#' Two execution modes controlled by \code{invest_amount}:
#'
#' \strong{All-In mode} (\code{invest_amount = 0}):
#' On a buy signal all available cash is deployed.  Stop-loss is checked
#' every day against \code{low_prices} — this intraday check is the primary
#' reason the loop runs in compiled C++ rather than interpreted R.
#' The check uses the daily low to catch intraday breaches: if the low
#' dips below the stop price the position is closed at the stop price.
#'
#' \strong{DCA / Accumulation mode} (\code{invest_amount > 0}):
#' Fresh-money model — on each buy signal \code{invest_amount} is added to
#' the cash balance (simulating a periodic salary contribution) and then
#' immediately invested.  Positions accumulate across signals; stop-loss is
#' not applied.  \code{cumulative_invested} tracks total capital deployed.
#'
#' Both modes use fractional shares — standard for index-fund / ETF
#' investing where the index level may greatly exceed the purchase amount.
#'
#' @param close_prices  Numeric vector of daily closing prices.
#' @param high_prices   Numeric vector of daily high prices (used for stop-loss).
#' @param low_prices    Numeric vector of daily low prices (used for stop-loss).
#' @param signals       Integer vector: 1 = buy signal, 0 = hold.
#' @param initial_cash  Starting cash balance (lump sum; 0 = pure DCA model).
#' @param stop_loss_pct Stop-loss fraction in [0, 1); 0 disables it.
#' @param invest_amount Periodic contribution per signal; 0 = all-in mode.
#' @return Named list with numeric vectors \code{equity}, \code{cash},
#'   \code{positions}, and \code{cumulative_invested}.
run_simulation_cpp <- function(close_prices, high_prices, low_prices, signals, initial_cash, stop_loss_pct, invest_amount) {
    .Call(`_quantlab_run_simulation_cpp`, close_prices, high_prices, low_prices, signals, initial_cash, stop_loss_pct, invest_amount)
}

