# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

run_simulation_cpp <- function(close_prices, high_prices, low_prices, signals, initial_cash, stop_loss_pct) {
    .Call(`_quantlab_run_simulation_cpp`, close_prices, high_prices, low_prices, signals, initial_cash, stop_loss_pct)
}

